version: "3.8"
services:
  db:
    image: postgres:14.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - "dbdata:/var/lib/postgresql/data"
volumes:
  dbdata:
